<?php

namespace Database\Factories;

use App\Models\Seller;
use App\Models\Store;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<\App\Models\Store>
 */
class StoreFactory extends Factory
{
    protected $model = Store::class;

    public function definition(): array
    {
        $name = $this->faker->company();

        return [
            'seller_id' => Seller::factory(),
            'name' => $name,
            // slug will be auto-generated by the model mutator when name is set

            // Address and location
            'address' => $this->faker->streetAddress(),
            'city' => $this->faker->city(),
            'landmark' => $this->faker->streetName(),
            'state' => $this->faker->state(),
            'zipcode' => (string) $this->faker->postcode(),
            'country' => $this->faker->country(),
            'country_code' => $this->faker->countryCode(),
            'latitude' => $this->faker->latitude(),
            'longitude' => $this->faker->longitude(),

            // Contacts
            'contact_email' => $this->faker->safeEmail(),
            'contact_number' => $this->faker->e164PhoneNumber(),

            // Optional texts
            'description' => $this->faker->optional()->realText(120),
            'store_url' => $this->faker->optional()->url(),
            'timing' => $this->faker->optional()->sentence(),

            // Required documents and banking
            'address_proof' => $this->faker->sentence(3),
            'voided_check' => $this->faker->sentence(3),
            'tax_name' => 'GST',
            'tax_number' => strtoupper($this->faker->bothify('??########')),
            'bank_name' => $this->faker->company() . ' Bank',
            'bank_branch_code' => strtoupper($this->faker->bothify('BR##')),
            'account_holder_name' => $this->faker->name(),
            'account_number' => (string) $this->faker->bankAccountNumber(),
            'routing_number' => (string) $this->faker->numerify('########'),
            'bank_account_type' => $this->faker->randomElement(['checking', 'savings']),
            'currency_code' => 'USD',

            // Configs and policies
            'max_delivery_distance' => $this->faker->randomFloat(1, 1, 25),
            'shipping_min_free_delivery_amount' => $this->faker->randomFloat(2, 0, 100),
            'shipping_charge_priority' => $this->faker->optional()->randomElement(['distance', 'flat']),
            'allowed_order_per_time_slot' => $this->faker->optional()->numberBetween(1, 10),
            'order_preparation_time' => $this->faker->numberBetween(5, 45),
            'carrier_partner' => $this->faker->optional()->word(),
            'promotional_text' => $this->faker->optional()->sentence(),
            'about_us' => $this->faker->paragraph(),
            'return_replacement_policy' => $this->faker->optional()->paragraph(),
            'refund_policy' => $this->faker->optional()->paragraph(),
            'terms_and_conditions' => $this->faker->optional()->paragraph(),
            'delivery_policy' => $this->faker->optional()->paragraph(),
            'shipping_preference' => $this->faker->optional()->sentence(),
            'domestic_shipping_charges' => $this->faker->optional()->randomFloat(2, 0, 50),
            'international_shipping_charges' => $this->faker->optional()->randomFloat(2, 0, 100),
            'metadata' => [],

            // Enums as strings
            'verification_status' => $this->faker->randomElement(['approved', 'not_approved']),
            'visibility_status' => $this->faker->randomElement(['visible', 'draft']),
            'fulfillment_type' => $this->faker->randomElement(['hyperlocal', 'regular', 'both']),
            'status' => $this->faker->randomElement(['online', 'offline']),
        ];
    }
}
